name: setup nodse
on: push
jobs:
  security:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3q
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run lint
      - name: run tests
        run: npm test # nam
